sudo: required
dist: trusty

language: python

matrix:
    include:
        - python: "3.6"
          env: COVERALLS=1

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  - pip install --upgrade coveralls
  - pip install numpy

script:
  - python setup.py build
  - if [ $COVERALLS = 1 ]; then
        coverage${PYVER} run --source=bristol setup.py test && coverage${PYVER} report -m;
    else
        python setup.py test;
    fi;

after_success:
- if [ $COVERALLS = 1 ]; then coveralls; fi;
